# Generated by Django 5.0.14 on 2026-08-24 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('type_bien', models.CharField(choices=[('villa', 'Villa'), ('appartement', 'Appartement'), ('immeuble', 'Immeuble'), ('terrain', 'Terrain')], max_length=20)),
                ('objectif', models.CharField(choices=[('louer', 'Louer'), ('vendre', 'Vendre'), ('les_deux', 'Les deux'), ('entretien', 'Entretien seul')], max_length=15)),
                ('adresse_bien', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours'), ('traite', 'Traité')], default='nouveau', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Demande de gestion',
                'verbose_name_plural': 'Demandes de gestion',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Propriétaire',
                'verbose_name_plural': 'Propriétaires',
            },
        ),
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('type_bien', models.CharField(choices=[('villa', 'Villa'), ('appartement', 'Appartement'), ('immeuble', 'Immeuble'), ('terrain', 'Terrain')], max_length=20)),
                ('transaction', models.CharField(choices=[('louer', 'À louer'), ('vendre', 'À vendre')], max_length=10)),
                ('ville', models.CharField(max_length=100)),
                ('quartier', models.CharField(blank=True, max_length=100)),
                ('prix', models.DecimalField(decimal_places=0, help_text='En FCFA (par mois si location)', max_digits=12)),
                ('chambres', models.PositiveSmallIntegerField(default=0)),
                ('superficie_m2', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='gestion/biens/')),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('reserve', 'Réservé'), ('loue', 'Loué'), ('vendu', 'Vendu')], default='disponible', max_length=15)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('proprietaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biens', to='gestion.proprietaire')),
            ],
            options={
                'verbose_name': 'Bien',
                'verbose_name_plural': 'Biens',
                'ordering': ['-date_creation'],
            },
        ),
    ]
