# Generated by Django 5.0.14 on 2026-08-24 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('type_bien', models.CharField(choices=[('villa', 'Villa'), ('immeuble', 'Immeuble'), ('rehabilitation', 'Réhabilitation')], max_length=20)),
                ('ville', models.CharField(max_length=100)),
                ('superficie_m2', models.PositiveIntegerField(verbose_name='Superficie (m²)')),
                ('superficie_terrain_m2', models.PositiveIntegerField(blank=True, null=True, verbose_name='Superficie terrain (m²)')),
                ('duree_mois', models.PositiveSmallIntegerField(verbose_name='Durée du chantier (mois)')),
                ('annee_livraison', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True)),
                ('image_principale', models.ImageField(upload_to='realisations/principales/')),
                ('en_avant', models.BooleanField(default=False, verbose_name="Mise en avant sur l'accueil")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Réalisation',
                'verbose_name_plural': 'Réalisations',
                'ordering': ['-annee_livraison', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='GalerieImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='realisations/galerie/')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('realisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galerie', to='realisations.realisation')),
            ],
            options={
                'verbose_name': 'Image de galerie',
                'verbose_name_plural': 'Images de galerie',
                'ordering': ['realisation', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='EtapeChantier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('duree', models.CharField(blank=True, help_text='Ex. « 3 semaines »', max_length=50)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('realisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='realisations.realisation')),
            ],
            options={
                'verbose_name': 'Étape de chantier',
                'verbose_name_plural': 'Étapes de chantier',
                'ordering': ['realisation', 'ordre'],
            },
        ),
    ]
