# Generated by Django 5.0.14 on 2026-08-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='vitrine/certifications/')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='MembreEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('poste', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vitrine/equipe/')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': "Membre de l'équipe",
                'verbose_name_plural': 'Équipe',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='StatistiqueCle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.SlugField(unique=True)),
                ('valeur', models.CharField(help_text='Ex. « 120+ », « 48 000 m² », « 9 »', max_length=20)),
                ('libelle', models.CharField(help_text='Ex. « Chantiers livrés »', max_length=100)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Statistique clé',
                'verbose_name_plural': 'Statistiques clés',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('role_client', models.CharField(help_text='Ex. « Propriétaire, Cocody »', max_length=150, verbose_name='Rôle / qualité')),
                ('texte', models.TextField()),
                ('note', models.PositiveSmallIntegerField(default=5, help_text='Note sur 5')),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='ValeurEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': "Valeur d'entreprise",
                'verbose_name_plural': "Valeurs d'entreprise",
                'ordering': ['ordre'],
            },
        ),
    ]
