# Generated by Django 5.0.14 on 2026-08-24 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('sujet', models.CharField(choices=[('conception', 'A — Conception (étude, plans, devis)'), ('realisation', 'B — Réalisation (construction)'), ('gestion', 'C — Gestion immobilière'), ('import_export', 'D — Import-export de matériaux'), ('autre', 'Autre demande')], default='autre', max_length=20)),
                ('message', models.TextField()),
                ('traite', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_traites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-date_creation'],
            },
        ),
    ]
