# Generated by Django 5.0.14 on 2026-08-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeEtude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ville_terrain', models.CharField(max_length=150, verbose_name='Ville / localisation du terrain')),
                ('superficie_terrain', models.CharField(blank=True, max_length=50, verbose_name='Superficie du terrain')),
                ('type_projet', models.CharField(choices=[('villa', 'Villa individuelle'), ('immeuble', 'Immeuble locatif'), ('rehabilitation', 'Réhabilitation'), ('autre', 'Autre')], default='villa', max_length=20)),
                ('message', models.TextField(blank=True, verbose_name='Votre projet en quelques mots')),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours de traitement'), ('traite', 'Traité'), ('archive', 'Archivé')], default='nouveau', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Demande d'étude",
                'verbose_name_plural': "Demandes d'étude",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PlanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('type_rendu', models.CharField(choices=[('plan_2d', 'Plan 2D'), ('rendu_3d', 'Rendu 3D')], default='plan_2d', max_length=10)),
                ('superficie', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(upload_to='conception/plans/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Plan-type',
                'verbose_name_plural': 'Plans-types',
                'ordering': ['ordre'],
            },
        ),
    ]
